---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: network-system
spec:
  interval: 5m
  chart:
    spec:
      chart: metallb
      version: 0.13.7
      sourceRef:
        kind: HelmRepository
        name: metallb-charts
        namespace: flux-system
      interval: 10m

  rollback:
    timeout: 10m
    recreate: true
    cleanupOnFail: true

  values:
    prometheus:
      namespace: system-monitoring
      serviceAccount: prometheus-prometheus
      podMonitor:
        enabled: true
      prometheusRule:
        enabled: true

    controller:
      resources:
        requests:
          cpu: 15m
          memory: 64M
        limits:
          cpu: 100m
          memory: 100M

    speaker:
      tolerateMaster: true
      resources:
        requests:
          cpu: 23m
          memory: 64M
        limits:
          cpu: 100m
          memory: 100M

    existingConfigMap: "metallb-config"
    crds:
      enabled: true

    tolerations:
      - effect: "NoSchedule"
        operator: "Exists"
