---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: truenas-workload-core-network-system-metallb
  namespace: flux-system
spec:
  interval: 10m
  path: ./manifests/truenas-workload/core/network-system/metallb
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-clusters
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: truenas-workload-core-network-system-metallb-custom-resources
  namespace: flux-system
spec:
  dependsOn:
    - name: truenas-workload-core-network-system-metallb
  interval: 10m
  path: ./manifests/truenas-workload/core/network-system/metallb/custom-resources/
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-clusters
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: truenas-workload-core-network-system-ingress-traefik
  namespace: flux-system
spec:
  dependsOn:
    - name: truenas-workload-core-network-system-metallb
  interval: 10m
  path: ./manifests/truenas-workload/core/network-system/traefik
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-clusters
  wait: true
