---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: truenas-workload-core-system-monitoring-kube-prometheus-stack
  namespace: flux-system
spec:
  interval: 10m
  path: ./manifests/truenas-workload/core/system-monitoring/kube-prometheus-stack
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-clusters
  wait: true
