---
apiVersion: v1
kind: Namespace
metadata:
  name: printing
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
    goldilocks.fairwinds.com/enabled: "true"
