---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: goldilocks
  namespace: system-monitoring
spec:
  dependsOn:
    - name: vpa
      namespace: system-monitoring
  interval: 5m
  chart:
    spec:
      chart: goldilocks
      version: 6.8.0
      sourceRef:
        kind: HelmRepository
        name: fairwinds-charts
        namespace: flux-system
      interval: 5m
  timeout: 20m
  install:
    remediation: # perform remediation when helm install fails
      retries: 3
  upgrade:
    remediation: # perform remediation when helm upgrade fails
      retries: 3
      remediateLastFailure: true # remediate the last failure, when no retries remain
    cleanupOnFail: true
  values:
    controller:
      resources:
        requests:
          cpu: 23m
          memory: 64M
        limits:
          cpu: 23m
          memory: 64M

    dashboard:
      replicaCount: 1
      resources:
        requests:
          cpu: 15m
          memory: 64M
        limits:
          cpu: 15m
          memory: 64M

      ingress:
        enabled: true
        ingressClassName: 'traefik'
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: 'web'
          hajimari.io/enable: 'true'
          hajimari.io/icon: ruler

        hosts:
          - host: &host 'goldilocks.${SECRET_DOMAIN}'
            paths:
              - path: /
                type: Prefix

        # tls:
        #   - hosts:
        #     - *host
