---
apiVersion: metal.sidero.dev/v1alpha1
kind: ServerClass
metadata:
  name: worker
spec:
  configPatches:
    - op: replace
      path: /machine/install/disk
      value: /dev/mmcblk0
    - op: add
      path: /machine/network
      value:
        interfaces:
          - interface: eth0
            dhcp: true
    - op: add
      path: /machine/kubelet/extraArgs
      value:
        rotate-server-certificates: true
  selector:
    matchLabels:
      pi-worker: "true"
