---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./pvc-config.yaml
  # - ./secret.sops.yaml
  - ./helmrelease.yaml
# patchesStrategicMerge:
#   - patches/postgres.yaml
