---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 5m
  timeout: 10m
  upgrade:
    remediation:
      remediateLastFailure: true
      strategy: rollback
  chart:
    spec:
      chart: cilium
      version: 1.14.1
      sourceRef:
        kind: HelmRepository
        name: cilium-charts
        namespace: flux-system
      interval: 5m
  values:
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
    cluster:
      name: cluster-vms
      id: 1
    rollOutCiliumPods: true
    localRedirectPolicy: true
    kubeProxyReplacement: strict
    kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
    ipv4NativeRoutingCIDR: 10.244.0.0/16
    k8sServiceHost: cp-vms.k8s.lmwpva.net
    k8sServicePort: 6443
    loadBalancer:
      algorithm: maglev
      mode: dsr
    tunnel: disabled
    endpointRoutes:
      enabled: true
    autoDirectNodeRoutes: true
    ipam:
      mode: kubernetes
    ipv6:
      enabled: false
    operator:
      rollOutPods: true
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true
    containerRuntime:
      integration: containerd
    securityContext:
      privileged: true
    hubble:
      enabled: true
      metrics:
        enabled:
          - dns:query
          - drop
          - flow
          - http
          - icmp
          - port-distribution
          - tcp
        serviceMonitor:
          enabled: true
      relay:
        enabled: true
        rollOutPods: true
      ui:
        enabled: true
        rollOutPods: true
        ingress:
          enabled: true
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: web
            # cert-manager.io/cluster-issuer: letsencrypt-production
            # cert-manager.io/cluster-issuer: letsencrypt-production
          hosts:
            - hubble.${SECRET_DOMAIN}
          # tls:
          #   - secretName: hubble-tls
          #     hosts:
          #       - hubble.${SECRET_DOMAIN}
    bgp:
      enabled: true
      announce:
        loadbalancerIP: true
