---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: hekate-apps
  namespace: flux-system
spec:
  kubeConfig:
    secretRef:
      name: hekate-kubeconfig
  interval: 10m0s
  dependsOn:
    - name: hekate-core
  sourceRef:
    kind: GitRepository
    name: k8s-clusters
    namespace: flux-system
  path: ./manifests/hekate/apps
  prune: true
  validation: client
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: Secret
        name: cluster-secrets-hekate
      - kind: ConfigMap
        name: cluster-settings-hekate
  decryption:
    provider: sops
    secretRef:
      name: sops-age
