---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  # name: apply-hekate-orchestration-core
  name: hekate-core
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: hekate-crds
    # - name: truenas-workload-namespaces
  kubeConfig:
    secretRef:
      name: hekate-kubeconfig
  # path: ./clusters/hekate/flux/orchestration/core
  path: ./manifests/hekate/core
  prune: true
  # wait: true
  sourceRef:
    kind: GitRepository
    name: k8s-clusters
    namespace: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings-hekate
      - kind: Secret
        name: cluster-secrets-hekate
