---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: truenas-workload-crds
  namespace: flux-system
spec:
  kubeConfig:
    secretRef:
      name: truenas-workload-kubeconfig
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: k8s-clusters
    namespace: flux-system
  path: ./manifests/truenas-workload/crds
  prune: false
  validation: client
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: Secret
        name: cluster-secrets-truenas-workload
      - kind: ConfigMap
        name: cluster-settings-truenas-workload
  decryption:
    provider: sops
    secretRef:
      name: sops-age
