---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: hekate-namespaces
  namespace: flux-system
spec:
  interval: 10m0s
  kubeConfig:
    secretRef:
      name: hekate-kubeconfig
  path: ./manifests/sidero-management/gitops/flux-system/cluster-sync/hekate/sync/namespaces
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-clusters
    namespace: flux-system
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: Secret
        name: cluster-secrets-hekate
      - kind: ConfigMap
        name: cluster-settings-hekate
  decryption:
    provider: sops
    secretRef:
      name: sops-age
