apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: truenas-workload
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 10.244.0.0/16
    services:
      cidrBlocks:
        - 10.96.0.0/12
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    kind: TalosControlPlane
    name: truenas-workload-cp
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: MetalCluster
    name: truenas-workload
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: MetalCluster
metadata:
  name: truenas-workload
  namespace: default
spec:
  controlPlaneEndpoint:
    host: cp-vms.k8s.lmwpva.net
    port: 6443
