---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: hekate-cluster
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: sidero-management-apps
  sourceRef:
    kind: GitRepository
    name: k8s-clusters
  path: ./clusters/hekate/talos
  prune: true
  # wait: true
