---
bgp:
  enabled: true
  announce:
    loadbalancerIP: true
hubble:
  relay:
    enabled: true
  ui:
    enabled: true
  tls:
    auto:
      method: cert-mangaer
ipam:
  mode: kubernetes
k8sServiceHost: cp-vms.k8s.lmwpva.net
k8sServicePort: 6443
