---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: metrics-server
      version: 3.8.3
      sourceRef:
        kind: HelmRepository
        name: metrics-server-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: k8s.gcr.io/metrics-server/metrics-server
      tag: v0.6.3

    # args:
    #   - --kubelet-insecure-tls

    tolerations:
      - effect: "NoSchedule"
        operator: "Exists"

    resources:
      requests:
        cpu: 35m
        memory: 64M
      limits:
        cpu: 100m
        memory: 200M
