---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: system-monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 48.3.4
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
    cleanupOnFail: true

  valuesFrom:
    # - kind: Secret
    #   name: kube-prometheus-stack
    #   valuesKey: discord-webhook
    #   targetPath: alertmanager.config.global.slack_api_url
    #   optional: false
    - kind: ConfigMap
      name: kps-generic-values
    - kind: ConfigMap
      name: kps-prometheus-values
    - kind: ConfigMap
      name: kps-alertmanager-values
