---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: MetalMachineTemplate
metadata:
  name: truenas-workload-cp
  namespace: flux-system
spec:
  template:
    spec:
      serverClassRef:
        apiVersion: metal.sidero.dev/v1alpha1
        kind: ServerClass
        name: master
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: TalosControlPlane
metadata:
  name: truenas-workload-cp
  namespace: flux-system
spec:
  controlPlaneConfig:
    controlplane:
      generateType: controlplane
      talosVersion: v1.2.5
      configPatches:
        - op: replace
          path: /machine/install/disk
          value: /dev/sda
        - op: add
          path: /machine/network
          value:
            interfaces:
              - interface: eth0
                dhcp: true
  infrastructureTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: MetalMachineTemplate
    name: truenas-workload-cp
  replicas: 3
  version: v1.25.1
