---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app node-red
  namespace: home-automation
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: ghcr.io/k8s-at-home/node-red
      tag: v3.0.2

    env:
      TZ: "{$TZ}"

    persistence:
      data:
        enabled: true
        existingClaim: node-red-data-v1
        mountPath: "/data"

    service:
      main:
        ports:
          http:
            port: 1880

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          # cert-manager.io/cluster-issuer: "letsencrypt-production"
          # cert-manager.io/cluster-issuer: 'selfsigned-cluster-issuer'
          hajimari.io/enable: "true"
          hajimari.io/icon: "resistor-nodes"
          hajimari.io/targetBlank: "true"
          traefik.ingress.kubernetes.io/router.entrypoints: "web"
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        # tls:
        #   - hosts:
        #       - *host
        #     secretName: 'node-red-tls'

    # podSecurityContext:
    #   # runAsUser: 568
    #   # runAsGroup: 568
    #   # fsGroup: 568
    #   runAsUser: 1
    #   runAsGroup: 1
    #   fsGroup: 1
    #   fsGroupChangePolicy: "OnRootMismatch"

    resources:
      requests:
        cpu: 22m
        memory: 164Mi
      limits:
        memory: 262Mi

    addons:
      codeserver:
        enabled: true
        image:
          repository: ghcr.io/coder/code-server
          tag: 4.9.1
        env:
          TZ: "${TZ}"
        volumeMounts:
          - name: data
            mountPath: /data
        ingress:
          enabled: true
          ingressClassName: "traefik"
          annotations:
            # cert-manager.io/cluster-issuer: "letsencrypt-production"
            # cert-manager.io/cluster-issuer: 'selfsigned-cluster-issuer'
            hajimari.io/enable: "true"
            hajimari.io/icon: "microsoft-visual-studio-code"
            hajimari.io/targetBlank: "true"
            traefik.ingress.kubernetes.io/router.entrypoints: "web"
          hosts:
            - host: &host "node-red-code.${SECRET_DOMAIN}"
              paths:
                - path: /
                  pathType: Prefix
