---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-red
  namespace: home-automation
spec:
  interval: 5m
  chart:
    spec:
      chart: truecharts/node-red
      version: 11.0.45
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      # repository: registry
      # tag: 3.0.2
    env:
      TZ: "Europe/Berlin"

    persistence:
      data:
        enabled: true
        existingClaim: node-red-data-v1

    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          # cert-manager.io/cluster-issuer: "letsencrypt-production"
          # cert-manager.io/cluster-issuer: 'selfsigned-cluster-issuer'
          hajimari.io/enable: "true"
          hajimari.io/icon: "resistor-nodes"
          traefik.ingress.kubernetes.io/router.entrypoints: "web"
        hosts:
          - host: &host "node-red.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        # tls:
        #   - hosts:
        #       - *host
        #     secretName: 'node-red-tls'

    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        memory: 96Mi
