---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apply-truenas-workload-cluster-orchestration-core
  namespace: flux-system
spec:
  dependsOn:
    - name: apply-truenas-workload-cluster-crds
    - name: apply-truenas-workload-cluster-namespaces
    - name: apply-truenas-workload-cluster-repositories
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  interval: 10m
  kubeConfig:
    secretRef:
      name: truenas-workload-kubeconfig
  path: ./clusters/truenas-workload/flux/orchestration/core
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-clusters
    namespace: flux-system
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings-truenas-workload
      - kind: Secret
        name: cluster-secrets-truenas-workload
  wait: true
  patches:
    - patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
        kind: Kustomization
        metadata:
          name: not-used
          namespace: not-used
        spec:
          decryption:
            provider: sops
            secretRef:
              name: sops-age
          postBuild:
            substitute: {}
            substituteFrom:
              - kind: ConfigMap
                name: cluster-settings-truenas-workload
              - kind: Secret
                name: cluster-secrets-truenas-workload
      target:
        kind: Kustomization
        group: kustomize.toolkit.fluxcd.io
        version: v1beta2
