---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apply-cluster-crds
  namespace: flux-system
spec:
  dependsOn:
    # - name: apply-cluster-config
    - name: apply-truenas-workload-cluster-repositories
    - name: apply-truenas-workload-cluster-manage-flux
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: home-cluster
  path: ./k8s/clusters/truenas-workload/crds/
  prune: true
  wait: true
