# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-hekate
    namespace: flux-system
stringData:
    CLUSTER_NAME: ENC[AES256_GCM,data:+VYwB65U,iv:nkXW5eEs1+vWXX2ROmpYyhmpelxxS+gff1T9NZ+9R1U=,tag:Iwuk5Sn/JeMZTCB88RSoAg==,type:str]
    CLUSTER_ID: ENC[AES256_GCM,data:2A==,iv:2yi1zQ6gADfoqZM3QVLtF2/6Kz7xGSihiElnAnu84Lo=,tag:NWXM/9iP3ZFTY0PLb9QwTg==,type:str]
    NAS_IP: ENC[AES256_GCM,data:jxaXzZ1d+R75ig==,iv:2WyWjZzN57QNqxXniMVKwt4S+lTC02072X62JyoLxH8=,tag:qup7Sh5dtnWG5cpUF9qBXA==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:/Sjj45mQML43opq6jtw=,iv:Jse0Lo6YxbRdDDhJs3G1Us880Kj/Qo1w5e80GnuBJjE=,tag:wuzH57wI7eSMYpurGdesEQ==,type:str]
    METALLB_LB_RANGE: ENC[AES256_GCM,data:9ohVKOXbr6ZYexeomh/xShUArG1jQZY=,iv:NNFLkO3hSN+V3SN2AogQKspMgqV7IiLEIpAZyFdkxzo=,tag:bLrrm5WMItg9zI9ydvRnTQ==,type:str]
    METALLB_TRAEFIK_ADDR: ENC[AES256_GCM,data:zyg8ztrFHOXAuIA=,iv:2b05zqeYAp2ZYt0Lcuke7H/e1Y/rMdu7ALHxSHU0ap8=,tag:uNWi/JzgZkWgNCMnUtDGag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18zy020jx8cykq89nnhgaz4ngp3c9ynr9dx7dr0zw7s55dwjxaplqv75k9p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuV3gvd2NIdWRqOWdFSGhJ
            MDdQQ0ZjNnJJeDdPWFN6UEdXdE9LRnBZbUZzCjVzVUgwaEwzdlZ0VVpEak1RNUhH
            R0ZMM2t6dVJxcTRQM3ZwVElmV0tDVE0KLS0tIHVEVi9OYVJsUUw1b2pVU0JyYi93
            WklOaDJiblo4SkNTTk5icUl4MTFNWDgK0+11BF4uzVQH8gHcVJHT/5b0dlajrskf
            kiJuE5k3AMGr3r4+nHRrHtL3nENw9wyq2Hg22DwxVuS733urHKn2VQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-24T22:05:15Z"
    mac: ENC[AES256_GCM,data:qtfwBNeOwqnmCdiTFrp3iwIrH9fji/I0vEaaoU9HBl3ArfgmQ2RUS0R5z2jUPbC1wLpv9EbRt2WuCUtLskyJseW8YJl6Nb4dprsMQ2cIJwSrS+xGdiiES8Lc+OJFgAq0f6Go2Dd1jDjpK5vzOlORBzF7IGlCRmGLw8QeURvgH/M=,iv:E7lVEc6DezHMY2SryNPhTpNN9AphU6LYJad2uAgPfSk=,tag:B1xeHeCz/flna1o6prZXPw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
