---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: user-printing-octoprint
  namespace: flux-system
spec:
  interval: 10m
  path: ./manifests/hekate/apps/printing/octoprint
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-clusters
  wait: true
