---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: sidero-management-core
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: sidero-management-crds
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./manifests/sidero-management/core
  prune: true
  validation: client
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: Secret
        name: cluster-secrets-sidero-management
      - kind: ConfigMap
        name: cluster-settings-sidero-management
  decryption:
    provider: sops
    secretRef:
      name: sops-age
