---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: sidero-management-gitops
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: k8s-clusters
  path: ./manifests/sidero-management/gitops
  prune: true
  # wait: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
