---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: home-automation
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: tccr.io/truecharts/eclipse-mosquitto
      tag: 2.0.15@sha256:a4b79ecfe66e7f676687745bafaacae4ab6566276ad4579cff09892875b85a7f
      pullPolicy: IfNotPresent

    # persistence:
    #   enabled: true
    #   size: 10Gi
    #   storageClass: nfs-client
    env:
      TZ: "${TZ}"

    persistence:
      data:
        enabled: true
        existingClaim: mosquitto-data-v1
      configinc:
        enabled: true
        existingClaim: mosquitto-configinc-v1

    # ingress:
    #   main:
    #     enabled: true
    #     ingressClassName: 'traefik'
    #     annotations:
    #       # cert-manager.io/cluster-issuer: "letsencrypt-production"
    #       # cert-manager.io/cluster-issuer: 'selfsigned-cluster-issuer'
    #       hajimari.io/enable: 'true'
    #       hajimari.io/icon: 'weather-sunset'
    #       traefik.ingress.kubernetes.io/router.entrypoints: 'web'
    #     hosts:
    #       - host: 'mosquitto.${SECRET_DOMAIN}'
    #         paths:
    #           - path: /
    #             pathType: Prefix
    #     # tls:
    #     #   - hosts:
    #     #       - 'mosquitto.${SECRET_DOMAIN}'
    #     #     secretName: 'mosquitto-tls'

    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        memory: 96Mi
