---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: home-automation
spec:
  interval: 5m
  chart:
    spec:
      chart: mosquitto
      version: 6.1.12
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    #image:
    # repository: registry
    #tag: v0.1.4
    # persistence:
    #   enabled: true
    #   size: 10Gi
    #   storageClass: nfs-client
    persistence:
      data:
        enabled: true
        existingClaim: mosquitto-data-v1
      configinc:
        enabled: true
        existingClaim: mosquitto-configinc-v1

    portal:
      enabled: true

    # ingress:
    #   main:
    #     enabled: true
    #     ingressClassName: 'traefik'
    #     annotations:
    #       # cert-manager.io/cluster-issuer: "letsencrypt-production"
    #       # cert-manager.io/cluster-issuer: 'selfsigned-cluster-issuer'
    #       hajimari.io/enable: 'true'
    #       hajimari.io/icon: 'weather-sunset'
    #       traefik.ingress.kubernetes.io/router.entrypoints: 'web'
    #     hosts:
    #       - host: 'mosquitto.${SECRET_DOMAIN}'
    #         paths:
    #           - path: /
    #             pathType: Prefix
    #     # tls:
    #     #   - hosts:
    #     #       - 'mosquitto.${SECRET_DOMAIN}'
    #     #     secretName: 'mosquitto-tls'
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        memory: 96Mi
