---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-data-v1
  namespace: home-automation
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-configinc-v1
  namespace: home-automation
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
