---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apply-cluster-deployment
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: k8s-clusters
  path: ./clusters/truenas-workload/flux/deploy
  prune: true
  wait: true
