---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: core-cert-manager-certmanager
  namespace: flux-system
spec:
  interval: 10m
  path: ./manifests/hekate/core/cert-manager/cert-manager/base
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-clusters
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: core-cert-manager-certmanager-config
  namespace: flux-system
spec:
  dependsOn:
    - name: core-cert-manager-certmanager
  interval: 10m
  path: ./manifests/hekate/core/cert-manager/cert-manager/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-clusters
  wait: true
