---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: core-kubelet-serving-cert-approver
  namespace: flux-system
spec:
  interval: 10m
  path: ./manifests/hekate/core/kubelet-serving-cert-approver
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-clusters
  wait: true
