---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: core-kube-system-nfs-subdir-external-provisioner
  namespace: flux-system
spec:
  interval: 10m
  path: ./manifests/hekate/core/kube-system/nfs-subdir-external-provisioner
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-clusters
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: core-kube-system-metrics-server
  namespace: flux-system
spec:
  interval: 10m
  path: ./manifests/hekate/core/kube-system/metrics-server
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-clusters
  wait: true
