---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: hekate-core-network-system-metallb
  namespace: flux-system
spec:
  interval: 10m
  path: ./manifests/hekate/core/network-system/metallb
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: k8s-clusters
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: hekate-core-network-system-metallb-custom-resources
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: hekate-core-network-system-metallb
  path: ./manifests/hekate/core/network-system/metallb/custom-resources/
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: k8s-clusters
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: hekate-core-network-system-ingress-traefik
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: hekate-core-network-system-metallb
  path: ./manifests/hekate/core/network-system/traefik
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: k8s-clusters
