---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: core-rook-ceph-operator
  namespace: flux-system
spec:
  interval: 10m
  path: ./manifests/hekate/core/rook-ceph/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-clusters
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: core-rook-ceph-cluster
  namespace: flux-system
spec:
  dependsOn:
    - name: core-rook-ceph-operator
  interval: 10m
  path: ./manifests/hekate/core/rook-ceph/cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-clusters
  wait: true
