---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apply-hekate-cluster-repositories
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  interval: 10m0s
  kubeConfig:
    secretRef:
      name: hekate-kubeconfig
  sourceRef:
    kind: GitRepository
    name: k8s-clusters
  path: ./clusters/hekate/flux/repositories
  prune: true
  wait: true
