---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apply-hekate-cluster-namespaces
  namespace: flux-system
spec:
  # dependsOn:
  #   - name: apply-manage-flux
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  interval: 10m
  kubeConfig:
    secretRef:
      name: hekate-kubeconfig
  sourceRef:
    kind: GitRepository
    name: k8s-clusters
  path: ./clusters/hekate/flux/namespaces
  prune: true
  wait: true
